### ISSUE TITLE
Downloading Chromium Pocket Browser

### ISSUE THREAD

**Issue by fxwgr** [burst-apps-team/Qbundle#4]
Like the topic says, I have a complete new installation, because the upgrade to the newest version didn't run well and now the installation repeats every time the step when downloading the chromium pocket browser package. Endlessly. Download. Delete. Download. Delete...
I also tried to start BurstWallet.exe with admin rights, no cure. Newest W10 is used.

**Comment by harryjph** [comment]
Can reproduce. Will take a look into this...

**Comment by harryjph** [comment]
Will be fixed in next release.

**Comment by fxwgr** [comment]
Fixed, thanks.
